/* Auto-generated by genmsg_cpp for file /home/mblanton/ROS_Packages/Acuity/msg/LaserRange.msg */
#ifndef ACUITY_MESSAGE_LASERRANGE_H
#define ACUITY_MESSAGE_LASERRANGE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace Acuity
{
template <class ContainerAllocator>
struct LaserRange_ {
  typedef LaserRange_<ContainerAllocator> Type;

  LaserRange_()
  : header()
  , range(0.0)
  {
  }

  LaserRange_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , range(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _range_type;
  float range;


  typedef boost::shared_ptr< ::Acuity::LaserRange_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Acuity::LaserRange_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct LaserRange
typedef  ::Acuity::LaserRange_<std::allocator<void> > LaserRange;

typedef boost::shared_ptr< ::Acuity::LaserRange> LaserRangePtr;
typedef boost::shared_ptr< ::Acuity::LaserRange const> LaserRangeConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::Acuity::LaserRange_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::Acuity::LaserRange_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace Acuity

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::Acuity::LaserRange_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::Acuity::LaserRange_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::Acuity::LaserRange_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cded8b3954e4ed742b2dd2e4170304d4";
  }

  static const char* value(const  ::Acuity::LaserRange_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xcded8b3954e4ed74ULL;
  static const uint64_t static_value2 = 0x2b2dd2e4170304d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::Acuity::LaserRange_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Acuity/LaserRange";
  }

  static const char* value(const  ::Acuity::LaserRange_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::Acuity::LaserRange_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# Single laser range reading from an active ranger.  NOTE: the sensor_msgs/Range.msg\n\
# was not used because that message is for sensors with a field of view, as opposed\n\
# to the laser range sensor which provides a point range.\n\
\n\
Header header    	# timestamp in the header is the time the ranger\n\
		 	# returned the distance reading\n\
\n\
float32 range       # range value (position) [m]\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::Acuity::LaserRange_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::Acuity::LaserRange_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::Acuity::LaserRange_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::Acuity::LaserRange_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.range);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct LaserRange_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Acuity::LaserRange_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::Acuity::LaserRange_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "range: ";
    Printer<float>::stream(s, indent + "  ", v.range);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ACUITY_MESSAGE_LASERRANGE_H

